#!/bin/sh
#needs banshee 0.10.6 and newer 
# By Ruben "RubenV" Vermeersch

if [ -z "$(pidof banshee)" ]; then
	echo 0
else 
	banshee --query-status --query-title --query-artist \
			--query-uri --query-cover-uri |sed  s/^﻿//
fi
exit 0
